### ISSUE TITLE
Issue when linking 2 elements with linked validation

### ISSUE THREAD

**Issue by nrso** [mdekrey/unobtrusive-angular-validation#1]
I'm trying to use your angular unobtrusive validation script and i'm actually having an issue.

What i would want to do is to link 2 validators of 2 elements in my form. I want to make a requiredIf where i have to fill at least one value of 2 inputs.

I've something like that:
input1 : 'some value'
input2: empty

when i clear input1 i would like that both input1 and input2 become invalid, thats something i'm able to do. I have both Input1 and Input2 invalid with the error message on both.
When i put then a value in input2 i'm able to set the validaty to true to input1 but i'm not able to clear the validation message
i do 
 angular.element(document.getElementById(input1)).data('$ngModelController').$setValidity('requiredif', true);
                angular.element(document.getElementById(input1)).data('$ngModelController').validationMessages = {};
                angular.element(document.getElementById(input1)).data('$ngModelController').suppressValidationMessages = false;

but the message is still there i have to blur the input 1 to make the message disapear.

So i'm doing it right or should i do it in another way ?

**Comment by mdekrey** [comment]
There is a data-val-if directive that can be used - I believe this would get the functionality you need.

<input data-val="true" data-val-if="!model.input2 || model.input1" data-val-required ng-model="model.input1" />
<input data-val="true" data-val-if="!model.input1 || model.input2" data-val-required ng-model="model.input2" />

Working off the top of my head here, but this should require one or the other, or both. (The || allows validation even if the other is filled in.)

**Comment by mdekrey** [comment]
Closing due to activity. `val-if` should handle the situation described.
