### ISSUE TITLE
Hiding validation messages for "pristine" fields

### ISSUE THREAD

**Issue by hades200082** [mdekrey/unobtrusive-angular-validation#2]
Is there a way to hide the validation messages for pristine fields?

**Comment by mdekrey** [comment]
I believe this is handled in the library as-written, unless you're suggesting after the submit button is pressed.  If that is the case, I'd recommend currently to use a data-val-if to test if the model is different from your default value.

If I'm wrong, or you have a suggestion for providing the default pristine value, could you provide a gist?

Thanks!

**Comment by hades200082** [comment]
I mean that we don't want the messages to appear just because the user has
clicked into the field and then on something else.

Currently the messages appear when the field is touched and invalid.

We want it to be when dirty and invalid instead.

Can this be done through configuration?

**Comment by mdekrey** [comment]
Ah, this can't be done yet, but is a good idea for an addition!

**Comment by hades200082** [comment]
Looks like Angular 1.3.5 added a new updateOn option for "submit" a couple of days ago.

https://github.com/angular/angular.js/issues/7017
https://github.com/angular/angular.js/commit/a0ae07bd4ee8d98654df4eb261d16ca55884e374

Not in their general release yet.

**Comment by mdekrey** [comment]
Using the updated version of angular, you can add `val-if="!inputName.$pristine"` as an attribute, and it should be picked up with prior versions. This will be added as a config-time option in the next major release for those that don't want to configure it per field.
